// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxspzihzbffbgqnyrtld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4c3B6aWh6YmZmYmdxbnlydGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDE3MTEsImV4cCI6MjA2MDIxNzcxMX0.73KXD1R8VGJWxGnvsfCOXBINAywMUVK1FIVsIfHJYRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);